name: monsterPlex
channels:
  - bioconda
  - conda-forge
dependencies:
  - _r-mutex=1.0.1=anacondar_1
  - bcftools=1.21=h48e1df0_1
  - bedtools=2.31.1=he85ad4a_3
  - bioconductor-ggtree=3.14.0=r44hdfd78af_0
  - bioconductor-treeio=1.30.0=r44hdfd78af_0
  - bowtie2=2.5.4=hdd4e3a4_5
  - bwidget=1.10.1=hce30654_0
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - clang=20.1.6=default_hcdeef69_0
  - clang-20=20.1.6=default_h03658f6_0
  - clangxx=20.1.6=default_haca757a_0
  - compiler-rt=20.1.6=hd2aecb6_0
  - curl=8.14.0=h73640d1_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=hce30654_1
  - fribidi=1.0.10=h27ca646_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.13=hebf3989_1003
  - gsl=2.7=h6e638da_0
  - harfbuzz=11.1.0=hab40de2_0
  - htslib=1.21=hfcd771d_1
  - icu=75.1=hfee45f7_0
  - isl=0.26=imath32_h347afa1_101
  - krb5=1.21.3=h237132a_0
  - lerc=4.0.0=hd64df32_1
  - libasprintf=0.24.1=h493aca8_0
  - libblas=3.9.0=31_h10e41b3_openblas
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libclang-cpp20.1=20.1.6=default_h03658f6_0
  - libcurl=8.14.0=h73640d1_0
  - libcxx=20.1.6=ha82da77_0
  - libcxx-devel=20.1.6=h6dc3340_0
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgettextpo=0.24.1=h493aca8_0
  - libgfortran=14.2.0=heb5dd2a_105
  - libgfortran5=14.2.0=h2c44a93_105
  - libglib=2.84.0=hdff4504_0
  - libiconv=1.18=hfe07756_1
  - libintl=0.24.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - libllvm20=20.1.6=h598bca7_0
  - liblzma=5.8.1=h39f12f2_1
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libpng=1.6.47=h3783ad8_0
  - libsqlite=3.50.1=h3f77e49_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.0=ha962b0a_2
  - libuv=1.51.0=h5505292_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxml2=2.13.8=h52572c6_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.6=hdb05f8b_0
  - llvm-tools=20.1.6=hd2aecb6_0
  - llvm-tools-20=20.1.6=h87a4c7e_0
  - make=4.4.1=hc9fafa5_2
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - ncurses=6.5=h5e97a16_3
  - openssl=3.5.0=h81ee809_1
  - pandoc=3.7.0.2=hce30654_0
  - pango=1.56.3=h5fd7515_1
  - pcre2=10.44=ha881caa_2
  - perl=5.32.1=7_h4614cfb_perl5
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.0=h2f9eb0b_0
  - python=3.13.5=h81fe080_101_cp313
  - python_abi=3.13=7_cp313
  - r-ape=5.8_1=r44h91c3ca0_0
  - r-aplot=0.2.5=r44hc72bb7e_0
  - r-askpass=1.2.1=r44h0d9a900_0
  - r-assertthat=0.2.1=r44hc72bb7e_5
  - r-backports=1.5.0=r44h07cda29_1
  - r-base=4.4.2=h9e409d2_1
  - r-base64enc=0.1_3=r44h07cda29_1007
  - r-brew=1.0_10=r44hc72bb7e_1
  - r-bslib=0.9.0=r44hc72bb7e_0
  - r-cachem=1.1.0=r44h07cda29_1
  - r-callr=3.7.6=r44hc72bb7e_1
  - r-cli=3.6.5=r44h31118f2_0
  - r-codetools=0.2_20=r44hc72bb7e_1
  - r-collections=0.3.8=r44h570997c_0
  - r-colorspace=2.1_1=r44h07cda29_0
  - r-commonmark=1.9.5=r44h570997c_0
  - r-cpp11=0.5.2=r44h785f33e_1
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-crosstalk=1.2.1=r44hc72bb7e_1
  - r-curl=6.2.2=r44h95ef94e_0
  - r-cyclocomp=1.1.1=r44hc72bb7e_1
  - r-desc=1.4.3=r44hc72bb7e_1
  - r-digest=0.6.37=r44hd76f289_0
  - r-dplyr=1.1.4=r44hd76f289_1
  - r-dt=0.33=r44hc72bb7e_1
  - r-ellipsis=0.3.2=r44h07cda29_3
  - r-evaluate=1.0.3=r44hc72bb7e_0
  - r-fansi=1.0.6=r44h07cda29_1
  - r-farver=2.1.2=r44hd76f289_1
  - r-fastmap=1.2.0=r44hd76f289_1
  - r-fontawesome=0.5.3=r44hc72bb7e_0
  - r-fs=1.6.6=r44h31118f2_0
  - r-future=1.49.0=r44h785f33e_0
  - r-generics=0.1.4=r44hc72bb7e_0
  - r-ggfun=0.1.8=r44hc72bb7e_0
  - r-ggplot2=3.5.2=r44hc72bb7e_0
  - r-ggplotify=0.1.2=r44hc72bb7e_1
  - r-ggrepel=0.9.6=r44hdd833ad_0
  - r-ggtext=0.1.2=r44hc72bb7e_3
  - r-globals=0.18.0=r44hc72bb7e_0
  - r-glue=1.8.0=r44h0d9a900_0
  - r-gridgraphics=0.5_1=r44hc72bb7e_3
  - r-gridtext=0.1.5=r44hd76f289_3
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-here=1.0.1=r44hc72bb7e_3
  - r-highr=0.11=r44hc72bb7e_1
  - r-htmltools=0.5.8.1=r44hd76f289_1
  - r-htmlwidgets=1.6.4=r44h785f33e_3
  - r-httpuv=1.6.15=r44hd76f289_1
  - r-httr2=1.1.2=r44hc72bb7e_0
  - r-isoband=0.2.7=r44hd76f289_3
  - r-jpeg=0.1_11=r44h8524b4b_0
  - r-jquerylib=0.1.4=r44hc72bb7e_3
  - r-jsonlite=2.0.0=r44h570997c_0
  - r-knitr=1.50=r44hc72bb7e_0
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-languageserver=0.3.16=r44h07cda29_1
  - r-later=1.4.2=r44h31118f2_0
  - r-lattice=0.22_7=r44h570997c_0
  - r-lazyeval=0.2.2=r44h07cda29_5
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-lintr=3.2.0=r44hc72bb7e_0
  - r-listenv=0.9.1=r44hc72bb7e_1
  - r-litedown=0.7=r44hc72bb7e_0
  - r-magrittr=2.0.3=r44h07cda29_3
  - r-markdown=2.0=r44hc72bb7e_0
  - r-mass=7.3_64=r44h570997c_0
  - r-matrix=1.7_3=r44hf6a007b_0
  - r-memoise=2.0.1=r44hc72bb7e_3
  - r-mgcv=1.9_3=r44he66de11_0
  - r-mime=0.13=r44h570997c_0
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_168=r44he0ea626_0
  - r-openssl=2.3.3=r44h3814a5a_0
  - r-parallelly=1.44.0=r44h570997c_0
  - r-patchwork=1.3.0=r44hc72bb7e_0
  - r-pillar=1.10.2=r44hc72bb7e_0
  - r-pkgbuild=1.4.8=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-pkgload=1.4.0=r44hc72bb7e_0
  - r-png=0.1_8=r44h272eed0_2
  - r-prettyunits=1.2.0=r44hc72bb7e_1
  - r-processx=3.8.6=r44h570997c_0
  - r-promises=1.3.2=r44h31118f2_0
  - r-ps=1.9.1=r44h570997c_0
  - r-purrr=1.0.4=r44h570997c_0
  - r-r.cache=0.17.0=r44hc72bb7e_0
  - r-r.methodss3=1.8.2=r44hc72bb7e_3
  - r-r.oo=1.27.1=r44hc72bb7e_0
  - r-r.utils=2.13.0=r44hc72bb7e_0
  - r-r6=2.6.1=r44hc72bb7e_0
  - r-rappdirs=0.3.3=r44h07cda29_3
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rcpp=1.0.14=r44h31118f2_0
  - r-rcpptoml=0.2.3=r44h31118f2_0
  - r-rematch2=2.1.2=r44hc72bb7e_4
  - r-remotes=2.5.0=r44hc72bb7e_1
  - r-repr=1.1.7=r44h785f33e_1
  - r-reticulate=1.42.0=r44h31118f2_0
  - r-rex=1.2.1=r44hc72bb7e_3
  - r-rlang=1.1.6=r44h31118f2_0
  - r-rmarkdown=2.29=r44hc72bb7e_0
  - r-roxygen2=7.3.2=r44hd76f289_1
  - r-rprojroot=2.0.4=r44hc72bb7e_1
  - r-sass=0.4.10=r44h31118f2_0
  - r-scales=1.4.0=r44hc72bb7e_0
  - r-shiny=1.10.0=r44h785f33e_0
  - r-shinydashboard=0.7.3=r44hc72bb7e_0
  - r-shinywidgets=0.9.0=r44hc72bb7e_0
  - r-sourcetools=0.1.7_1=r44hd76f289_2
  - r-spscomps=0.3.3.0
  - r-stringi=1.8.7=r44h4f22b37_0
  - r-stringr=1.5.1=r44h785f33e_1
  - r-styler=1.10.3=r44hc72bb7e_1
  - r-sys=3.4.3=r44h0d9a900_0
  - r-tibble=3.2.1=r44h07cda29_3
  - r-tidyr=1.3.1=r44hd76f289_1
  - r-tidyselect=1.2.1=r44hc72bb7e_1
  - r-tidytree=0.4.6=r44hc72bb7e_1
  - r-tinytex=0.57=r44hc72bb7e_0
  - r-utf8=1.2.5=r44h570997c_0
  - r-vctrs=0.6.5=r44hd76f289_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-withr=3.0.2=r44hc72bb7e_0
  - r-xfun=0.52=r44h31118f2_0
  - r-xml2=1.3.8=r44h1f9de2a_0
  - r-xmlparsedata=1.0.5=r44hc72bb7e_3
  - r-xtable=1.8_4=r44hc72bb7e_6
  - r-yaml=2.3.10=r44h07cda29_0
  - r-yulab.utils=0.2.0=r44hc72bb7e_0
  - raxml=8.2.13=hbdacb55_3
  - readline=8.2=h1d1bf99_2
  - samtools=1.21=h267f7b9_1
  - sigtool=0.1.3=h44b9a77_0
  - tabix=1.11=hdfd78af_0
  - tapi=1300.6.5=h03f4b80_0
  - tk=8.6.13=h892fb3f_2
  - tktable=2.10=h1e387b8_6
  - tzdata=2025b=h78e105d_0
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h6491c7d_2
